- name: install nginx server
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: run app pre-requisites
  aansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req.yaml

- name: copy backend conf
  ansible.builtin.template:
    src: expense.conf.j3
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - restart nginx
  

#- name: restart nginx
#  ansible.builtin.service:
#    name: nginx
#    state: restarted