- name: install mysqlserver
  ansible.builtin.dnf:
    name: mysqlserver
    state: latest

- name: enable and start mysql server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: install python mysql dependencies
  ansible.builtin.pip:
    name:
    - PyMySQL
    - cryptography
    executable: pip3.9 # pip3.11 if python version is 3.11

- name: Check mysql  Connectivity
  community.mysql.mysql_info:
    login_user: root
    login_host: "{{ login_host }}"
    login_password: "{{ mysql_root_password }}"
    filter: version
    ignore_errors: yes
    register: mysql_connectivity_output

- name: print mysql_connectivity_output
  ansible.builtin.debug:
    msg: "{{ mysql_connectivity_output }}"

- name: create root mySql login_password
  ansible.builtin.command: mysql_secure_installation --set-root-pass "{{ mysql_root_password }}"
  when: mysql_connectivity_output.faile is true